#!/bin/python2

import sys, os.path
from jinja2 import Environment, FileSystemLoader

paramFile=sys.argv[1]
templateFile=sys.argv[2]
resultFile=sys.argv[3]

d = {}
with open(paramFile) as f:
    for line in f:
        line = line.strip()
        # Ignore comments and blank lines
        if not line.startswith("#") and line:
            #(key, val) = line.split()
            linelist = line.split()
            print linelist
            key = linelist[0]
            val = ' '.join(linelist[1:])
            d[key] = val

env = Environment(loader=FileSystemLoader('./'))
template = env.get_template(templateFile)
render = template.render(d)

truncate=False
exists=os.path.isfile(resultFile)
# First open to  know if the file has changed ('r')
if exists:
    with open(resultFile, 'r') as f:
        if (f.read() != render):
            truncate=True
if (truncate or not exists):
    # Second open to overwrite as new file ('w')
    with open(resultFile, 'w') as f:
        f.write(render)

