#!/bin/python2

import sys, os.path
from jinja2 import Environment, FileSystemLoader
import yaml

paramFile=sys.argv[1]
templateFile=sys.argv[2]
resultFile=sys.argv[3]

with open(paramFile, 'r') as stream:
    try:
        d = yaml.load(stream)
    except yaml.YAMLError as exc:
        print(exc)            

env = Environment(loader=FileSystemLoader('./'))
template = env.get_template(templateFile)
render = template.render(d)

truncate=False
exists=os.path.isfile(resultFile)
# First open to  know if the file has changed ('r')
if exists:
    with open(resultFile, 'r') as f:
        if (f.read() != render):
            truncate=True
if (truncate or not exists):
    # Second open to overwrite as new file ('w')
    with open(resultFile, 'w') as f:
        f.write(render)

